power/urls.py
from django.conf.urls import url
from . import views

app_name = 'power'

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^govt_login/',views.govt_login, name='govt_login'),
    url(r'^govt_signup/',views.govt_signup, name='govt_signup'),
    url(r'^user_login/',views.user_login, name='user_login'),
    url(r'^user_signup/',views.user_signup, name='user_signup'),
    url(r'^logout/',views.logout, name='logout'),   
    url(r'^add_board/',views.add_board, name='add_board'),   
    # url(r'^view_board/',views.view_board, name='view_board'),   
    url(r'^govt_dash/',views.govt_dash, name='govt_dash'),
    url(r'^user_dash/',views.user_dash, name='user_dash'),
    url(r'^edit_profile/',views.edit_profile, name='edit_profile'),   
    url(r'^search/',views.search, name='search'),   
    url(r'^get_data/(?P<id>\d+)/',views.scraping, name='scraping'), 
    url(r'^change_password/',views.change_password, name='change_password'), 
    url(r'^enable_notifications/',views.enable_notifications, name='enable_notifications'), 
    url(r'^scraping/',views.scraping, name='scraping'), 
    url(r'^scrap_data/',views.scrap_data, name='scrap_data'), 



    url(r'^analysis/',views.analysis, name='analysis'),
    url(r'^save_table/',views.save_table, name='save_table'),
    url(r'^get_data/',views.get_data, name='get_data'),
    url(r'^history/',views.history, name='history'),
    url(r'^alert/',views.alert, name='alert'),
    url(r'^getalert/',views.getalert, name='getalert'),
    url(r'^sendmailall/',views.sendmailall, name='sendmailall'),
    url(r'^addalert/',views.addalert, name='addalert'),


]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^power/', include('power.urls')),
]

power/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    aadhar = models.CharField(max_length=12, default="000012340000")
    mob = models.CharField(max_length=100, default="0000")
    is_user = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    

class Sector(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Board(models.Model):
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    state = models.CharField(max_length=100)
    url = models.TextField(max_length=1000, default="http://www.mperc.in/consolidated-reg.htm")
    xpath = models.TextField(max_length=1000, default="/html/body/table/tbody/tr/td/div/center/table[1]/tbody/tr/td[6]/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr[2]/td[69]")
    person = models.ForeignKey(Person,on_delete=models.CASCADE)
    modified = models.CharField(max_length=100, default="Today")

    def __str__(self):
        return self.name

class Notification(models.Model):
    uid = models.IntegerField()
    bid = models.IntegerField()
    
class Table(models.Model):
    uid = models.IntegerField(default=2)
    name = models.CharField(max_length=100)
    url = models.TextField(max_length=1000, default = 'https://www.upsldc.org/real-time-data')
    xpath = models.TextField(max_length=1000, default = '/html/body/div[2]/div[2]/div/div/div/div/div/div/div/div[1]/div/div/div/div[2]/div/div/div[2]/table')

    def __str__(self):
        return self.name


class Alert(models.Model):
    uid = models.IntegerField(default=2)
    name = models.CharField(max_length=100)
    starttime = models.CharField(max_length=100)
    endtime = models.CharField(max_length=100)
    key = models.CharField(max_length=100)
    avgvalue = models.CharField(max_length=100)
    minmattr = models.CharField(max_length=100)
    minmvalue = models.CharField(max_length=100)
    maxmattr = models.CharField(max_length=100)
    maxmvalue = models.CharField(max_length=100)
    attr = models.IntegerField(default=0)

    def __str__(self):
        return self.name

power/views.py
from django.shortcuts import render,redirect, get_object_or_404

from django.http import HttpResponse,JsonResponse
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys

from .models import Person,Sector,Board, Notification, Table, Alert


import time
import pandas as pd
from django.core.mail import send_mail
import json


################# CURRENT ###################

def save_table(request):
	t = Table()
	if Table.objects.filter(name=request.POST['name'],uid=request.session['uid']).exists() == False:
		t.name = request.POST['name']
		t.url = request.POST['url']
		t.xpath = request.POST['xpath']
		t.uid = request.session['uid']
		t.save()
		request.session['table_name'] = t.name
	return redirect('/power/analysis')

def analysis(request):
	# downloadpdftest('./chromedriver', 'https://secure-video-calling.herokuapp.com/' )
	# downloadpdf('./chromedriver', 'https://npp.gov.in/publishedReports')
	# minms = {'Actual_flow':6020, 'Frequency':55}
	# maxms = {'Actual_flow':6200, 'Frequency':65}
	# x = getfile("./download/Notice 2020 - Sheet1.csv", minms, maxms)
	# print(x)
	if request.GET.get('tablename'):
		request.session['table_name'] = request.GET.get('tablename')
	context = {}
	if 'uid' in request.session:
		uid = request.session['uid']
	else:
		return HttpResponse("Please Login")
	if 'table_name' in request.session:
		context['table_name'] = request.session['table_name']
		context['data'] = Table.objects.get(uid=uid,name=request.session['table_name'])
	
	return render(request, 'power/analysis.html', context)

# def get_data(request):
# 	# table_name = request.POST['table_name']
# 	# t = get_object_or_404(Table, name = table_name)
# 	# url = t.url
# 	url = 'https://www.upsldc.org/real-time-data'
# 	# xpath = t.xpath
# 	xpath = '/html/body/div[2]/div[2]/div/div/div/div/div/div/div/div[1]/div/div/div/div[2]/div/div/div[2]/table'
# 	data = downloadbyxpath('./chromedriver', url, xpath)
	
# 	return JsonResponse(data, safe=False)

# url = 'https://www.delhisldc.org/'
# 	# 
# 	xpath = '/html/body/form/div[3]/table/tbody/tr[5]/td/table/tbody/tr[2]/td[2]/table/tbody/tr[1]/td/table'
def get_data(request):
	table_name = request.POST['table_name']
	t = get_object_or_404(Table, name = table_name, uid=request.session['uid'])
	url = t.url
	xpath = t.xpath
	
	data = downloadbyxpath('/usr/bin/chromedriver', url, xpath)

	return JsonResponse(data, safe=False)


def downloadbyxpath(chromedriverpath, url, xpath):

	options = Options()
	options.headless = True
	options.add_argument("--headless")

	driver = webdriver.Chrome(chromedriverpath,options=options)
	driver.maximize_window()
	driver.get(url)

	ele = driver.find_elements_by_xpath(xpath+"/tbody/tr")
	keys = []
	values = []
	for val in ele:
		cur = val.text
		arr = cur.split(' ')
		key = ""
		for i in range(0,len(arr)-1):
			key = key + arr[i]
		value = arr[len(arr)-1]
		keys.append(key)
		values.append(value)

	ret = {0:keys, 1:values}
	return ret

def history(request):
	if 'uid' in request.session:
		uid = request.session['uid']
		results = Table.objects.filter(uid=uid)
		return render(request, 'power/history.html', context={"results":results})
	else:
		return HttpResponse("Please Login")


def alert(request):
	if 'uid' in request.session:
		uid = request.session['uid']
		results = Alert.objects.filter(uid=uid)
		return render(request, 'power/alerts.html', context={"results":results})
	else:
		return HttpResponse("Please Login")


def getalert(request):
	alertid = request.GET.get('alertid')
	print(alertid)
	alert = Alert.objects.get(pk=alertid)
	print(alert)
	return render(request, 'power/get_alert.html', context={"alert":alert})


def sendmailall(request):
	uid = request.session['uid']
	user_det = Person(pk=uid)
	data = Alert.objects.filter(uid=uid)
	ret = {}
	ret_html = {}
	i=0
	for val in data:
		res = {'Table Name' : val.name, 'Type' : val.key, 'Avy Value' : val.avgvalue, 'Start Time' : val.starttime, 'End Time' : val.endtime}
		ret[i] = res
		html = "       " 
		html += "           Table Name :  "+val.name
		html += "          Type : "+val.key
		html += "          Avg Value : "+val.avgvalue

		html += "          Start Time : "+val.starttime
		html += "          End Time : "+val.endtime

		html += "                  " 
		ret_html[i] = html
		i = i+1
	ret = json.dumps(ret)
	ret_html = json.dumps(ret_html)
	print(ret_html)

	send_mail(
		'Alerts to Power Sector of India',
		ret_html,
		'rishikeshsahu14101998@gmail.com',
		['rishikeshsahu2017@gmail.com'],
		fail_silently=False,
	)
	return HttpResponse("SuccesFully Mailed to your Account")


def addalert(request):
	name = request.POST.get('name')
	freq = request.POST.get('freq')
	starttime = request.POST.get('starttime')
	endtime = request.POST.get('endtime')
	minmfreq = request.POST.get('minmfreq')
	maxmfreq = request.POST.get('maxmfreq')
	print(name)
	print(freq)
	print(starttime)
	print(minmfreq)

	user_det = Person(pk=request.session['uid'])

	a = Alert()
	a.uid = request.session['uid']
	a.name = name
	a.key = "Frequency"
	a.avgvalue = freq
	a.starttime = starttime
	a.endtime = endtime
	a.minmattr = "Minm Frequency"
	a.minmvalue = minmfreq
	a.maxmattr = "Maxm Frequency"
	a.maxmvalue = maxmfreq
	a.save()


	html = "       " 
	html += "           Table Name :  "+name
	html += "          Type : Frequency"
	html += "          Avg Value : "+freq
	html += "          Start Time : "+starttime
	html += "          End Time : "+endtime
	html += "                  " 

	send_mail(
		'Alerts to Power Sector of India',
		html,
		'rishikeshsahu14101998@gmail.com',
		['rishikeshsahu2017@gmail.com'],
		fail_silently=False,
	)



	return HttpResponse("Success")
# def savedcharts(request):
# 	if 'uid' in request.session:
# 		uid = request.session['uid']
# 		results = Chart.objects.filter(uid=uid)
# 		return render(request, 'power/savedcharts.html', context={"results":results})
# 	else:
# 		return HttpResponse("Please Login")

###################### //// CURRENT #################


def index(request):
	message = ""
	message_type = ""
	if 'message' in request.session:
		message = request.session['message']
	
	if 'type' in request.session:
		message_type = request.session['type']
		
	request.session['message']=""

	return render(request,'power/index.html', context = {"message": message, "type" : message_type, "homelink":1})

def user_login(request):

	print(request.POST)
	email = request.POST['email']
	password = request.POST['password']
	print("inside user login====================")

	if Person.objects.filter(email=email, password=password, is_user=True).exists():
		p = Person.objects.get(email=email)
		request.session['uid']=p.id
		request.session['name']=p.name
		request.session['is_user']=p.is_user
		request.session['message']="Successfully Logged in";
		request.session['type'] = 1
		return redirect('/power/user_dash/')
	else:
		print("wrong email or password===============")
		request.session['message']="Wrong Email or Password";
		request.session['type'] = ""
		return redirect('/power/')



def user_signup(request):
	name = request.POST['name']
	email = request.POST['email']
	password = request.POST['password']

	if Person.objects.filter(email=email).exists():
		request.session['message']="Email Already Exists";
		request.session['type'] = ""
		return redirect('/power/')
	else:
		p = Person(name = name, email=email, password=password)
		p.save()
		request.session['uid']=p.id
		request.session['is_user']=p.is_user
		request.session['name']=p.name
		request.session['message']="Successfully Logged in";
		request.session['type'] = 1

		return redirect('/power/user_dash') 


def govt_login(request):
	email = request.POST['email']
	password = request.POST['password']

	if Person.objects.filter(email=email, password=password, is_user=False).exists():
		p = Person.objects.get(email=email)
		request.session['name']=p.name
		request.session['is_user']=p.is_user
		request.session['uid']=p.id
		request.session['message']="Successfully Logged in";
		request.session['type'] = 1
		return redirect('/power/govt_dash')
	else:
		request.session['message']="Wrong Email or Password";
		request.session['type'] = ""
		return redirect('/power/')


def govt_signup(request):
	name = request.POST['name']
	email = request.POST['email']
	password = request.POST['password']
	print("======inside govt signup=========")
	if Person.objects.filter(email=email).exists():
		print("=====email exists=======")
		request.session['message']="Email Already Exists";
		request.session['type'] = ""
		return redirect('/power/')
	else:
		p = Person(name = name, email=email, password=password, is_user=False)
		p.save()
		request.session['name']=p.name
		request.session['is_user']=p.is_user
		request.session['uid']=p.id
		print("=====logged in success=======")
		request.session['message']="Successfully Logged in";
		request.session['type'] = 1
		return redirect('/power/govt_dash') 



def logout(request):
	if 'uid' in request.session:
		del request.session['uid']
		del request.session['name']
		del request.session['is_user']
	request.session['message']="Successfully Logged out";
	request.session['type'] = 1
	return redirect('/power/')



def govt_dash(request):

	if 'uid' not in request.session:
		request.session['message']="Please login first"
		request.session['type']=""  # dont know the type

		redirect('/power/')

	uid = request.session['uid']
	
	p = Person.objects.get(pk=uid)
	all_boards = p.board_set.all()
	all_sectors = Sector.objects.all()
	all_states = Board.objects.values_list('state',flat=True).distinct().order_by('state')
	# all_boards = all_boards.value_list('sector', flat=True).order_by('sector')
	# print(type(all_states[0]))
	state = "all"
	sector = "555"

	# what if it comes through GET?
	if request.method == "POST":
		state = request.POST['state']
		sector = request.POST['sector']	

		if Sector.objects.filter(pk=sector).exists():
			# selected_sector = Sector.objects.get(pk=sector)

power/templates/power/alerts.html
{% extends 'power/base.html' %}

{% block title %}dashboard{% endblock title %}



{% block body %}
<script>
function search(val){
    $.ajax({
        method : "POST",
        url:"{% url 'power:search' %}",
        data : {
            "search":val,
            "sector":"{{sector}}",
            "state":"{{state}}",
            "csrfmiddlewaretoken": '{{ csrf_token }}',
        },
        success : function(result){
            {% comment %} console.log(result); {% endcomment %}
            
            var x = document.getElementById("tbody1");
            var i=0;
            text="";
            for(; i<result.length; i++){
                
                row =   "<tr>\n"+
                        "    <th>"+(i+1)+"</th>\n"+
                        "    <td>"+result[i]['name']+"</td>\n"+
                        "    <td>"+result[i]['sector']+"</td>\n"+
                        "    <td>"+result[i]['state']+"</td>\n"+
                        "    <td>"+"28 July, 2012"+"</td>\n"+
                        '    <td><a target="__blank" class="my-btn2" href="/power/get_data/'+result[i].id+'/">See Details</a></td>\n'+
                        "</tr>\n";
                text +=row;
            }
                
            x.innerHTML = text;
            {% comment %} console.log(result); {% endcomment %}
        }
    });
}
</script>
<style type="text/css" link="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></style>




{% if message %}
{% if type %}
<div id="alert" style="position: fixed;right: 20px;top: 40px;" class="alert alert-success" role="alert">
  {{message}}
</div>
{% else %}
<div id="alert" style="position: fixed;right: 20px;top: 40px;" class="alert alert-danger" role="alert">
  {{message}}
</div>
{% endif %}
{% endif %}
<style type="text/css">
    .fa-bell{
        font-size: 120px;
    }
    a{
        color: rgb(50,50,50);
    }
    a:hover{
        color: rgb(50,50,50);
    }
</style>
<div class="content-wrapper">
<div class="container-fluid">
    <div class="row pt-5">
        <div class="col-md-12">
            <div class="container-fluid">
                <a class="btn btn-lg about-us-btn" onclick="sendMail()" href="#" role="button">MAIL ME</a>
                <div class="row">

                    {% for result in results %}
                    <div class="col-md-2 col-6 p-3">
    					<a href="/power/getalert?alertid={{result.pk}}" class="card text-center p-2" style="height: 240px;">
                         <i class="far fa-bell"></i>
                          <div style="padding: 0px;" class="card-body">
                            <h6 class="card-title mt-3">{{result.name}}</h6>
                            {% if result.attr %}
                            <p><b>Type : </b>Power Drawl</p>
                            {% else %}
                            <p><b>Type : </b>Frequency</p>
                            {% endif %}
                          </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div> 
</div>


{% endblock body %}

{% block custom_header %}
    <!-- <li class="nav-item">
        <a class="nav-link" href="{% url 'power:add_board' %}">Add</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'power:view_board' %}">View</a>
    </li> -->
    <!-- <li class="nav-item">
        <a class="nav-link" href="{% url 'power:edit_profile' %}">Edit Profile</a>
    </li> -->
{% endblock custom_header %}

{% block custom_header_right %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'power:user_dash' %}">{{request.session.name}}<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item dropdown user-icon">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" ><i class="fas fa-user"></i></a>
    <div class="dropdown-menu dropdown-menu-right">
        <a href="{% url 'power:edit_profile' %}" class="dropdown-item">Edit Profile</a>
        <div class="dropdown-divider"></div>
        <a href="{% url 'power:logout' %}"class="dropdown-item">Logout</a>
    </div>
</li>
<li><i class="fas fa-caret-down pt-3 pl-2"></i></li>

{% endblock custom_header_right %}

{% block apply_filter %}

<!-- Apply Filter Modal -->
<div class="modal fade" id="filtermodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">APPLY FILTER</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'power:user_dash' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label style="padding: 0px;" for="state" class="col-12"><h4>State</h4></label>
                <select name="state" id="state" class="form-control" value="all">
                    <option id="all_st" value="all">All States</option>
                    {% for state in all_states %}
                        <option id="{{state}}" value="{{state}}">{{state}}</option>
                    {% endfor %}
                    
                </select>
                <!-- <select name="state" id="state" class="form-control">
                    <option value="Andhra Pradesh">Andhra Pradesh</option>
                    <option value="Arunachal Pradesh">Arunachal Pradesh</option>
                    <option value="Assam">Assam</option>
                    <option value="Bihar">Bihar</option>
                    <option value="Chattisgarh">Chattisgarh</option>
                    <option value="Goa">Goa</option>
                </select> -->
            </div>
            <div class="form-group">
                <label style="padding: 0px;" for="sector" class="col-12"><h4>Sector</h4></label>
                <select name="sector" id="sector" class="form-control" value="555">
                    <option id="555" value="555">All Sectors</option>
                    {% for sector in all_sectors %}
                        <option id="{{sector.id}}" value="{{sector.id}}">{{sector.name}}</option>
                    {% endfor %}
                </select>
                <!-- <select name="sector" id="sector" class="form-control">
                    <option value="Coal">Coal</option>
                    <option value="Electricity">Electricity</option>
                    <option value="Petroleum">Petroleum</option>
                </select> -->
            </div>
            <button type="submit" class="btn btn-primary my-btn"><i class="fas fa-chevron-right"></i></button>
        </form>
        <p class="mt-3">
          Unable to find your board?
          <a href="#" data-toggle="modal" data-target="#contactmodal" data-dismiss="modal">Email US</a>
      </p>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.js"></script>
<script type="text/javascript">
  $("#alert").fadeOut(3000);
  var state="";
  var sector="";
  window.onload = function() {
    state = "{{state}}";
    sector = "{{sector}}";
    document.getElementById("state").value = state;
    document.getElementById("sector").value = sector;
  }


  function sendMail() {
    $.ajax({
        method : "POST",
        url:"{% url 'power:sendmailall' %}",
        async: false,
        data : {
            "csrfmiddlewaretoken": '{{ csrf_token }}',
        },
        success : function(result){
            alert(result);
        }
    });
  }
</script>

{% endblock apply_filter %}

power/templates/power/scrap_data.html
{% extends 'power/base.html' %}

{% block title %}dashboard{% endblock title %}

{% block body %}
<script>
var is_enabled="{{enable}}";
function enable_notifications(board_id){
    if(is_enabled=="") is_enabled=0;
    enable=parseInt(is_enabled);

    enable=1-enable;
    is_enabled=enable;
    $.ajax({
        method : "POST",
        url:"{% url 'power:enable_notifications' %}",
        data : {
            "board_id":board_id,
            "csrfmiddlewaretoken": '{{ csrf_token }}',
        },
        success : function(result){
            console.log(enable);
            if(enable==1) {
                document.getElementById('notifications').innerHTML = "Disable Notifications";
            }else {
                document.getElementById('notifications').innerHTML = "Enable Notifications";
            }
        }
    });
}
</script>

<div class="content-wrapper">
<div id="edit_profile" class="container-fluid">
    <div class="row pt-4">
        
        <div class="col-md-5">
            <div class="row">
                <h3 class="ml-3 mb-3">{{board.name}}</h3>
                <div class="container">
                    <form>
                        {% csrf_token %}
                        <div class='form-group row'>
                            <label for='firstname' class='col-md-3 col-form-label'>Sector</label>
                            <div class='col-md-9'>
                                <input disabled="true" type='text' class='form-control' id='firstname' name='sector'
                                    value="{{board.sector}}">
                            </div>
                        </div>
                        <div class='form-group row'>
                            <label for='firstname' class='col-md-3 col-form-label'>State</label>
                            <div class='col-md-9'>
                                <input disabled="true" type='text' class='form-control' id='firstname' name='sector'
                                    value="{{board.state}}">
                            </div>
                        </div>
                        <div class='form-group row'>
                            <label for='lastname' class='col-md-3 col-form-label'>Page URL</label>
                            <div class='col-md-9'>
                                <input disabled="" type='text' class='form-control' id='url' name='url'
                                    value="{{board.url}}">
                            </div>
                        </div>
                        <input disabled="" type='hidden' class='form-control' id='xpath' name='xpath' value="{{board.xpath}}">
                        <div class='form-group row'>
                            <label for='mobileno' class='col-12 col-md-3 col-form-label'>Last Modified</label>
                            <div class='col-5 col-md-9'>
                                <input disabled="" type='tel' class='form-control' id='mobileno' name='modified'
                                    value="{{ message }}">
                            </div>
                        </div>
                        <!-- <div class='form-group row'>
                            <label for='aadhar' class='col-md-2 col-form-label'>Aadhar No.</label>
                            <div class='col-md-10'>
                                <p>Show Aadhar no here</p>
                            </div>
                        </div> -->
                        
                        <div class='form-group row'>
                            <a href="/power/user_dash" data-toggle="tooltip" data-placement="top" title="Go Back" type="submit" class="btn btn-primary my-btn ml-3"><i class="fas fa-chevron-left"></i></a>
                            {% if enable %}
                            <a href="#" class='btn my-btn3 ml-3' id='notifications' onclick="enable_notifications({{board.id}})" >Disable Notifications</a>
                            
                            {% else %}
                            <a href="#" class='btn my-btn3 ml-3' id='notifications' onclick="enable_notifications({{board.id}})" >Enable Notifications</a>
                            {% endif %}
                            <div id="loader" class="loader ml-4 mt-1"></div>
                        </div>
                    </form>
                    
                    
                </div>
            </div>
        </div>
        <div class="col-md-7">
            <div id="scrap_data" class="jumbotron p-3" style="background: transparent;overflow-x: scroll;"></div>
        </div>
    </div>
    

</div>
</div>


<script type="text/javascript">
    var csrftoken = $("[name=csrfmiddlewaretoken]").val();
    document.getElementById('scrap_data').style.display = "none";

    function loadData() {
        url = document.getElementById('url').value;
        xpath = document.getElementById('xpath').value;
        document.getElementById('scrap_data').style.display = "none";
        document.getElementById('loader').style.display = "block";
        $.ajax({
            url: "/power/scrap_data/",
            method : "POST",
            headers:{
                "X-CSRFToken": csrftoken
            },
            data:{"url": url, "xpath":xpath},
            cache:true,
            success: function(result){
                document.getElementById('loader').style.display = "none";
                document.getElementById('scrap_data').style.display = "block";
                document.getElementById('scrap_data').innerHTML = result;

                arr = url.split('/');
                baseurl = arr[0] + '//' + arr[2] + '/';
                $("#scrap_data a").each(function(){
                    $(this).attr("href", baseurl + $(this).attr("href"));
                });
            }
        });
    }
    loadData();

    window.setInterval(function(){loadData();}, 30000);
</script>



{% endblock body %}

{% block custom_header %}
    <li class="nav-item">
        <a class="nav-link active" href="#">Edit Profile</a>
    </li>
{% endblock custom_header %}

{% block custom_header_right %}

{% if request.session.is_user %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'power:user_dash' %}">{{request.session.name}} <span class="sr-only">(current)</span></a>
</li>
{% else %}
<li class="nav-item">
    <a class="nav-link" href="{% url 'power:govt_dash' %}">{{request.session.name}} <span class="sr-only">(current)</span></a>
</li>
{% endif %}

<li class="nav-item dropdown user-icon">
    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fas fa-user"></i></a>
    <div class="dropdown-menu dropdown-menu-right">
        <a href="{% url 'power:edit_profile' %}" class="dropdown-item">Edit Profile</a>
        <div class="dropdown-divider"></div>
        <a href="{% url 'power:logout' %}"class="dropdown-item">Logout</a>
    </div>
</li>
<li><i class="fas fa-caret-down pt-3 pl-2"></i></li>

{% endblock custom_header_right %}