power/urls.py
from django.conf.urls import url
from . import views

app_name = 'power'

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^govt_login/',views.govt_login, name='govt_login'),
    url(r'^govt_signup/',views.govt_signup, name='govt_signup'),
    url(r'^user_login/',views.user_login, name='user_login'),
    url(r'^user_signup/',views.user_signup, name='user_signup'),
    url(r'^logout/',views.logout, name='logout'),   
    url(r'^add_board/',views.add_board, name='add_board'),   
    # url(r'^view_board/',views.view_board, name='view_board'),   
    url(r'^govt_dash/',views.govt_dash, name='govt_dash'),
    url(r'^user_dash/',views.user_dash, name='user_dash'),
    url(r'^edit_profile/',views.edit_profile, name='edit_profile'),   
    url(r'^search/',views.search, name='search'),   
    url(r'^get_data/(?P<id>\d+)/',views.scraping, name='scraping'), 
    url(r'^change_password/',views.change_password, name='change_password'), 
    url(r'^enable_notifications/',views.enable_notifications, name='enable_notifications'), 
    url(r'^scraping/',views.scraping, name='scraping'), 
    url(r'^scrap_data/',views.scrap_data, name='scrap_data'), 



    url(r'^analysis/',views.analysis, name='analysis'),
    url(r'^save_table/',views.save_table, name='save_table'),
    url(r'^get_data/',views.get_data, name='get_data'),
    url(r'^history/',views.history, name='history'),
    url(r'^alert/',views.alert, name='alert'),
    url(r'^getalert/',views.getalert, name='getalert'),
    url(r'^sendmailall/',views.sendmailall, name='sendmailall'),
    url(r'^addalert/',views.addalert, name='addalert'),


]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^power/', include('power.urls')),
]

power/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    aadhar = models.CharField(max_length=12, default="000012340000")
    mob = models.CharField(max_length=100, default="0000")
    is_user = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    

class Sector(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Board(models.Model):
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    state = models.CharField(max_length=100)
    url = models.TextField(max_length=1000, default="http://www.mperc.in/consolidated-reg.htm")
    xpath = models.TextField(max_length=1000, default="/html/body/table/tbody/tr/td/div/center/table[1]/tbody/tr/td[6]/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr[2]/td[69]")
    person = models.ForeignKey(Person,on_delete=models.CASCADE)
    modified = models.CharField(max_length=100, default="Today")

    def __str__(self):
        return self.name

class Notification(models.Model):
    uid = models.IntegerField()
    bid = models.IntegerField()
    
class Table(models.Model):
    uid = models.IntegerField(default=2)
    name = models.CharField(max_length=100)
    url = models.TextField(max_length=1000, default = 'https://www.upsldc.org/real-time-data')
    xpath = models.TextField(max_length=1000, default = '/html/body/div[2]/div[2]/div/div/div/div/div/div/div/div[1]/div/div/div/div[2]/div/div/div[2]/table')

    def __str__(self):
        return self.name


class Alert(models.Model):
    uid = models.IntegerField(default=2)
    name = models.CharField(max_length=100)
    starttime = models.CharField(max_length=100)
    endtime = models.CharField(max_length=100)
    key = models.CharField(max_length=100)
    avgvalue = models.CharField(max_length=100)
    minmattr = models.CharField(max_length=100)
    minmvalue = models.CharField(max_length=100)
    maxmattr = models.CharField(max_length=100)
    maxmvalue = models.CharField(max_length=100)
    attr = models.IntegerField(default=0)

    def __str__(self):
        return self.name

power/views.py
from django.shortcuts import render,redirect, get_object_or_404

from django.http import HttpResponse,JsonResponse
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys

from .models import Person,Sector,Board, Notification, Table, Alert


import time
import pandas as pd
from django.core.mail import send_mail
import json


################# CURRENT ###################

def save_table(request):
	t = Table()
	if Table.objects.filter(name=request.POST['name'],uid=request.session['uid']).exists() == False:
		t.name = request.POST['name']
		t.url = request.POST['url']
		t.xpath = request.POST['xpath']
		t.uid = request.session['uid']
		t.save()
		request.session['table_name'] = t.name
	return redirect('/power/analysis')

def analysis(request):
	# downloadpdftest('./chromedriver', 'https://secure-video-calling.herokuapp.com/' )
	# downloadpdf('./chromedriver', 'https://npp.gov.in/publishedReports')
	# minms = {'Actual_flow':6020, 'Frequency':55}
	# maxms = {'Actual_flow':6200, 'Frequency':65}
	# x = getfile("./download/Notice 2020 - Sheet1.csv", minms, maxms)
	# print(x)
	if request.GET.get('tablename'):
		request.session['table_name'] = request.GET.get('tablename')
	context = {}
	if 'uid' in request.session:
		uid = request.session['uid']
	else:
		return HttpResponse("Please Login")
	if 'table_name' in request.session:
		context['table_name'] = request.session['table_name']
		context['data'] = Table.objects.get(uid=uid,name=request.session['table_name'])
	
	return render(request, 'power/analysis.html', context)

# def get_data(request):
# 	# table_name = request.POST['table_name']
# 	# t = get_object_or_404(Table, name = table_name)
# 	# url = t.url
# 	url = 'https://www.upsldc.org/real-time-data'
# 	# xpath = t.xpath
# 	xpath = '/html/body/div[2]/div[2]/div/div/div/div/div/div/div/div[1]/div/div/div/div[2]/div/div/div[2]/table'
# 	data = downloadbyxpath('./chromedriver', url, xpath)
	
# 	return JsonResponse(data, safe=False)

# url = 'https://www.delhisldc.org/'
# 	# 
# 	xpath = '/html/body/form/div[3]/table/tbody/tr[5]/td/table/tbody/tr[2]/td[2]/table/tbody/tr[1]/td/table'
def get_data(request):
	table_name = request.POST['table_name']
	t = get_object_or_404(Table, name = table_name, uid=request.session['uid'])
	url = t.url
	xpath = t.xpath
	
	data = downloadbyxpath('/usr/bin/chromedriver', url, xpath)

	return JsonResponse(data, safe=False)


def downloadbyxpath(chromedriverpath, url, xpath):

	options = Options()
	options.headless = True
	options.add_argument("--headless")

	driver = webdriver.Chrome(chromedriverpath,options=options)
	driver.maximize_window()
	driver.get(url)

	ele = driver.find_elements_by_xpath(xpath+"/tbody/tr")
	keys = []
	values = []
	for val in ele:
		cur = val.text
		arr = cur.split(' ')
		key = ""
		for i in range(0,len(arr)-1):
			key = key + arr[i]
		value = arr[len(arr)-1]
		keys.append(key)
		values.append(value)

	ret = {0:keys, 1:values}
	return ret

def history(request):
	if 'uid' in request.session:
		uid = request.session['uid']
		results = Table.objects.filter(uid=uid)
		return render(request, 'power/history.html', context={"results":results})
	else:
		return HttpResponse("Please Login")


def alert(request):
	if 'uid' in request.session:
		uid = request.session['uid']
		results = Alert.objects.filter(uid=uid)
		return render(request, 'power/alerts.html', context={"results":results})
	else:
		return HttpResponse("Please Login")


def getalert(request):
	alertid = request.GET.get('alertid')
	print(alertid)
	alert = Alert.objects.get(pk=alertid)
	print(alert)
	return render(request, 'power/get_alert.html', context={"alert":alert})


def sendmailall(request):
	uid = request.session['uid']
	user_det = Person(pk=uid)
	data = Alert.objects.filter(uid=uid)
	ret = {}
	ret_html = {}
	i=0
	for val in data:
		res = {'Table Name' : val.name, 'Type' : val.key, 'Avy Value' : val.avgvalue, 'Start Time' : val.starttime, 'End Time' : val.endtime}
		ret[i] = res
		html = "       " 
		html += "           Table Name :  "+val.name
		html += "          Type : "+val.key
		html += "          Avg Value : "+val.avgvalue

		html += "          Start Time : "+val.starttime
		html += "          End Time : "+val.endtime

		html += "                  " 
		ret_html[i] = html
		i = i+1
	ret = json.dumps(ret)
	ret_html = json.dumps(ret_html)
	print(ret_html)

	send_mail(
		'Alerts to Power Sector of India',
		ret_html,
		'rishikeshsahu14101998@gmail.com',
		['rishikeshsahu2017@gmail.com'],
		fail_silently=False,
	)
	return HttpResponse("SuccesFully Mailed to your Account")


def addalert(request):
	name = request.POST.get('name')
	freq = request.POST.get('freq')
	starttime = request.POST.get('starttime')
	endtime = request.POST.get('endtime')
	minmfreq = request.POST.get('minmfreq')
	maxmfreq = request.POST.get('maxmfreq')
	print(name)
	print(freq)
	print(starttime)
	print(minmfreq)

	user_det = Person(pk=request.session['uid'])

	a = Alert()
	a.uid = request.session['uid']
	a.name = name
	a.key = "Frequency"
	a.avgvalue = freq
	a.starttime = starttime
	a.endtime = endtime
	a.minmattr = "Minm Frequency"
	a.minmvalue = minmfreq
	a.maxmattr = "Maxm Frequency"
	a.maxmvalue = maxmfreq
	a.save()


	html = "       " 
	html += "           Table Name :  "+name
	html += "          Type : Frequency"
	html += "          Avg Value : "+freq
	html += "          Start Time : "+starttime
	html += "          End Time : "+endtime
	html += "                  " 

	send_mail(
		'Alerts to Power Sector of India',
		html,
		'rishikeshsahu14101998@gmail.com',
		['rishikeshsahu2017@gmail.com'],
		fail_silently=False,
	)



	return HttpResponse("Success")
# def savedcharts(request):
# 	if 'uid' in request.session:
# 		uid = request.session['uid']
# 		results = Chart.objects.filter(uid=uid)
# 		return render(request, 'power/savedcharts.html', context={"results":results})
# 	else:
# 		return HttpResponse("Please Login")

###################### //// CURRENT #################


def index(request):
	message = ""
	message_type = ""
	if 'message' in request.session:
		message = request.session['message']
	
	if 'type' in request.session:
		message_type = request.session['type']
		
	request.session['message']=""

	return render(request,'power/index.html', context = {"message": message, "type" : message_type, "homelink":1})

def user_login(request):

	print(request.POST)
	email = request.POST['email']
	password = request.POST['password']
	print("inside user login====================")

	if Person.objects.filter(email=email, password=password, is_user=True).exists():
		p = Person.objects.get(email=email)
		request.session['uid']=p.id
		request.session['name']=p.name
		request.session['is_user']=p.is_user
		request.session['message']="Successfully Logged in";
		request.session['type'] = 1
		return redirect('/power/user_dash/')
	else:
		print("wrong email or password===============")
		request.session['message']="Wrong Email or Password";
		request.session['type'] = ""
		return redirect('/power/')



def user_signup(request):
	name = request.POST['name']
	email = request.POST['email']
	password = request.POST['password']

	if Person.objects.filter(email=email).exists():
		request.session['message']="Email Already Exists";
		request.session['type'] = ""
		return redirect('/power/')
	else:
		p = Person(name = name, email=email, password=password)
		p.save()
		request.session['uid']=p.id
		request.session['is_user']=p.is_user
		request.session['name']=p.name
		request.session['message']="Successfully Logged in";
		request.session['type'] = 1

		return redirect('/power/user_dash') 


def govt_login(request):
	email = request.POST['email']
	password = request.POST['password']

	if Person.objects.filter(email=email, password=password, is_user=False).exists():
		p = Person.objects.get(email=email)
		request.session['name']=p.name
		request.session['is_user']=p.is_user
		request.session['uid']=p.id
		request.session['message']="Successfully Logged in";
		request.session['type'] = 1
		return redirect('/power/govt_dash')
	else:
		request.session['message']="Wrong Email or Password";
		request.session['type'] = ""
		return redirect('/power/')


def govt_signup(request):
	name = request.POST['name']
	email = request.POST['email']
	password = request.POST['password']
	print("======inside govt signup=========")
	if Person.objects.filter(email=email).exists():
		print("=====email exists=======")
		request.session['message']="Email Already Exists";
		request.session['type'] = ""
		return redirect('/power/')
	else:
		p = Person(name = name, email=email, password=password, is_user=False)
		p.save()
		request.session['name']=p.name
		request.session['is_user']=p.is_user
		request.session['uid']=p.id
		print("=====logged in success=======")
		request.session['message']="Successfully Logged in";
		request.session['type'] = 1
		return redirect('/power/govt_dash') 



def logout(request):
	if 'uid' in request.session:
		del request.session['uid']
		del request.session['name']
		del request.session['is_user']
	request.session['message']="Successfully Logged out";
	request.session['type'] = 1
	return redirect('/power/')



def govt_dash(request):

	if 'uid' not in request.session:
		request.session['message']="Please login first"
		request.session['type']=""  # dont know the type

		redirect('/power/')

	uid = request.session['uid']
	
	p = Person.objects.get(pk=uid)
	all_boards = p.board_set.all()
	all_sectors = Sector.objects.all()
	all_states = Board.objects.values_list('state',flat=True).distinct().order_by('state')
	# all_boards = all_boards.value_list('sector', flat=True).order_by('sector')
	# print(type(all_states[0]))
	state = "all"
	sector = "555"

	# what if it comes through GET?
	if request.method == "POST":
		state = request.POST['state']
		sector = request.POST['sector']	

		if Sector.objects.filter(pk=sector).exists():
			# selected_sector = Sector.objects.get(pk=sector)

power/templates/power/old/base_old.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    
    

    <title>{% block title %}power{% endblock title %}</title>
    <style>
      body{
        background-color: rgb(50,50,50);
      }
      nav{
        border-radius: 0 0 15px 15px;
      }
      .content-wrapper{
        background-color: white;
        min-height: 550px;
        height: 100%;
        margin: 12px 12px 0 12px;
        border-radius: 15px 15px 0 0;
      }
      .user-icon {
        border :  1px solid rgb(50,50,50);
        padding: 2px 8px;
        border-radius: 50%;
        font-size: 16px;
        cursor: pointer;
      }
      .dropdown-toggle::after{
        display: none;
      }
      .my-menu{
        position: absolute;
        left: -50px;
        min-width: 8rem;
      }
      .my-btn{
        background-color: #00408B;
        border-radius: 50%;
        padding: 8px 16px;
      }
      a:hover{text-decoration: none;}
      li.active a{
        color: #00408B !important;
      }
      li a{
        color: black !important;
      }
      .about-us-btn{
        color: #00408B;
        border:1px solid #00408B;
        border-radius: 30px;
        padding: 8px 30px;
        font-size: 15px;
      }
      .about-us-btn:hover{
        background-color: #00408B;
        color: #fff;
      }
    </style>
</head>
<body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"> </script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'power:index' %}">Potential</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'power:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'power:index' %}">Services <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'power:index' %}">Contact<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'power:user_dash' %}">User Dash<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'power:govt_dash' %}">Govt Dash<span class="sr-only">(current)</span></a>
            </li>
            
            
            
            </ul>
            <!--<form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> -->
            <ul class="nav navbar-nav ml-auto">
            {% block custom_header_right %}
            
                <li class="nav-item user-icon dropdown">
                    <a class="nav-link dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i></a>
                    <div class="dropdown-menu my-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" data-toggle="modal" data-target="#loginmodal" href="#">User</a>
                    <a class="dropdown-item" data-toggle="modal" data-target="#adminloginmodal" href="#">Admin</a>
                  </div>
                </li>
                <li><i class="fas fa-caret-down pt-3 pl-2"></i></li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'power:govt_login' %}">Govt Login</a>
                </li> -->

                   
            {% endblock custom_header_right %}
            </ul> 
        </div>
    </nav>
    
    {% block body %}
    {% endblock body %}
</body>
</html>

<!-- User Signin Modal -->
<div class="modal fade" id="loginmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">LOGIN AS USER</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'power:user_login' %}" method="post">
          {% csrf_token %}
          <div class="form-group">
              <label for="email">Email address</label>
              <input type="email" class="form-control" name="email" id="email" placeholder="Enter email">
          </div>
          <div class="form-group">
              <label for="password">Password</label>
              <input type="password" class="form-control" name="password" id="password" placeholder="Password">
          </div>
          <button type="submit" class="btn btn-primary my-btn"><i class="fas fa-chevron-right"></i></button>
      </form>    
      <p class="mt-2">
          Don't Have an Account?
          <a href="#" data-toggle="modal" data-target="#signupmodal" data-dismiss="modal">Sign up</a>
          .
      </p>
      </div>
    </div>
  </div>
</div>

<!-- User Signup Modal -->
<div class="modal fade" id="signupmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">CREATE AN ACCOUNT</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'power:user_signup' %}" method="post">
          {% csrf_token %}
          <div class="form-group">
              <label for="name">Full Name</label>
              <input type="text" class="form-control" id="name" name="name" placeholder="Enter Full Name">
          </div>
          <div class="form-group">
              <label for="email">Email address</label>
              <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
          </div>
          <div class="form-group">
              <label for="password">Password</label>
              <input type="password" class="form-control" name="password" id="password" placeholder="Password">
          </div>
          <button type="submit" class="btn btn-primary my-btn"><i class="fas fa-chevron-right"></i></button>
      </form>    
      <p class="mt-2">
          Already Have an Account?
          <a href="#" data-toggle="modal" data-target="#loginmodal" data-dismiss="modal">Login</a>
          .
      </p>
      </div>
    </div>
  </div>
</div>





<!-- User Signin Modal -->
<div class="modal fade" id="adminloginmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">LOGIN AS ADMIN</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'power:govt_login' %}" method="post">
          {% csrf_token %}
          <div class="form-group">
              <label for="email">Email address</label>
              <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
          </div>
          <div class="form-group">
              <label for="password">Password</label>
              <input type="password" class="form-control" name="password" id="password" placeholder="Password">
          </div>
          <button type="submit" class="btn btn-primary my-btn"><i class="fas fa-chevron-right"></i></button>
      </form>    
      <p class="mt-2">
          Don't Have an Account?
          <a href="#" data-toggle="modal" data-target="#adminsignupmodal" data-dismiss="modal">Sign up</a>
          .
      </p>
      </div>
    </div>
  </div>
</div>

<!-- User Signup Modal -->
<div class="modal fade" id="adminsignupmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">CREATE AN ACCOUNT</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'power:govt_signup' %}" method="post">
          {% csrf_token %}
          <div class="form-group">
              <label for="name">Full Name</label>
              <input type="text" class="form-control" name="name" id="name" placeholder="Enter Full Name">
          </div>
          <div class="form-group">
              <label for="email">Email address</label>
              <input type="email" class="form-control" name="email" id="email" placeholder="Enter email">
          </div>
          <div class="form-group">
              <label for="password">Password</label>
              <input type="password" class="form-control" name="password" id="password" placeholder="Password">
          </div>
          <button type="submit" class="btn btn-primary my-btn"><i class="fas fa-chevron-right"></i></button>
      </form>    
      <p class="mt-2">
          Already Have an Account?
          <a href="#" data-toggle="modal" data-target="#adminloginmodal" data-dismiss="modal">Login</a>
          .
      </p>
      </div>
    </div>
  </div>
</div>

power/templates/power/old/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'power:index' %}">Power</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'power:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      {% block custom_header %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'power:user_login' %}">User Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'power:govt_login' %}">Govt Login</a>
        </li>
      {% endblock custom_header %}
      
      <li class="nav-item">
        <a class="nav-link" href="#">Logout</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>